#+TITLE: blog
#+CATEGORY: blog
#+STARTUP: overview 
#+startup: hidestars
Just my personal blog.

***** TODOs
** TODO Draft and create 'about me' section 			      :draft:
 DEADLINE: <2015-08-28 Fr>
 :PROPERTIES:
 :Created: [2015-06-22 Mo 11:47]
 :Assigned_to: kordano
 :END:

* License

Copyright © 2015 Konrad Kühne

Distributed under the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details: <http://www.gnu.org/licenses/>.
>>>>>>> c7a4a7f84a87493a738ded8f2ef30a873e64115e
